### ISSUE TITLE
Replace UTests that access database with DAO or something else

### ISSUE THREAD

**Issue by sdfraga** [abapinho/abaK#21]
**ZCL_ABAK_SOURCE_RFC** Unit Test **VALID** is failing.

![image](https://user-images.githubusercontent.com/16186872/55705352-e4ef2380-59de-11e9-80ad-93f7da768d8a.png)

I believe the issue is in the content of ZABAK table..
After the latest PULL the content of the table is:

![image](https://user-images.githubusercontent.com/16186872/55705269-b6714880-59de-11e9-99ad-1b1a331d7a52.png)

**Comment by nununo** [comment]
There shouldn't even be unit tests depending on the database. These have to be removed.

The solution could be introducing DAOs like @Sdfraga proposed:
https://blogs.sap.com/2013/03/21/abap-unit-tests-without-database-dependency-dao-concept/

Let's try.

**Comment by nununo** [comment]
Fixed by 83766c914931cf140e9ad95168962dd09a9d6167
