### ISSUE TITLE
BC set throws error, DEMO program dumps

### ISSUE THREAD

**Issue by moniker23** [abapinho/abaK#22]
![image](https://user-images.githubusercontent.com/49623891/56100224-3daa4900-5f16-11e9-8b4d-dfdef65be915.png)

**Comment by moniker23** [comment]
![image](https://user-images.githubusercontent.com/49623891/56100235-6599ac80-5f16-11e9-8ac5-332288d5bb33.png)

tested on Netweaver 7.51 (Developer edition)

**Comment by nununo** [comment]
Hi, I hope https://github.com/abapinho/abaK/pull/24 solved this. Please let me know.

**Comment by nununo** [comment]
I cannot test it but I will assume the changes done by @Sdfraga solved this issue. Please feel free to reopen it if you find that there are still problems @moniker23. Thanks.
